[[main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[main]]
  name = "Gallery"
  weight = 2
  identifier = "gallery"
  url = "/image/"

[[main]]
  name = "Channel"
  weight = 3
  identifier = "channel"
  url = "/video/"

[[main]]
  name = "Links"
  weight = 4
  identifier = "links"
  url = "/link/"

[[main]]
  name = "Search"
  weight = 5
  identifier = "search"
  url = "/search/"
  post = "<svg aria-hidden=\"true\" class=\"i-search\" viewBox=\"0 0 32 32\" width=\"14\" height=\"14\" fill=\"none\" stroke=\"currentcolor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"3\"><circle cx=\"14\" cy=\"14\" r=\"12\" /><path d=\"M23 23 L30 30\" /></svg>"