description = "Hope of Survival" # Suggested, controls default description meta
author = "Aigeanta" # Optional, controls author name display on posts
hide_author = false # Optional, set true to hide author name on posts
disable_csp = true # Optional, set true to disable content security policy
images = [
  "/images/header/aigeanta-background.png"
] # Suggested, controls default Open Graph images

[layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[layout.footer]
  hidden = false # Optional, set true to hide footer

[layout.home]
  hide_blog = false

[[layout.home.section]]
  type = "about"
  weight = 1

[[layout.home.section]]
  type = "story" # Required, name of section to show on homepage
  limit = 3 # Optional, set number of items to show from section
  weight = 2 # Optional, choose layout order for section

[[layout.home.section]]
  type = "blog" # Required, name of section to show on homepage
  limit = 6 # Optional, set number of items to show from section
  weight = 3 # Optional, choose layout order for section

[modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

[modules.hall_of_mirrors]
  enabled = true # Required in version 0.x.x
