description = "Hope of Survival" # Suggested, controls default description meta
author = "Aigeanta" # Optional, controls author name display on posts
hide_author = false # Optional, set true to hide author name on posts
disable_csp = false # Optional, set true to disable content security policy
images = [
  "/images/header/aigeanta-background.png"
] # Suggested, controls default Open Graph images
related_content_limit = 5 # limit to 5 items maximum site-wide
[layout.post.related]
  limit = 3

[layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[layout.footer]
  hidden = false # Optional, set true to hide footer

[layout.home]
  hide_blog = true

[[layout.home.section]]
  type = "blog"
  limit = 3 # Optional, set number of items to show from section
  weight = 1

[[layout.home.section]]
  type = "story" # Required, name of section to show on homepage
  limit = 3 # Optional, set number of items to show from section
  weight = 2 # Optional, choose layout order for section

[[layout.home.section]]
  type = "image" # Required, name of section to show on homepage
  limit = 3 # Optional, set number of items to show from section
  weight = 3 # Optional, choose layout order for section

[[layout.home.section]]
  type = "video" # Required, name of section to show on homepage
  limit = 3 # Optional, set number of items to show from section
  weight = 4 # Optional, choose layout order for section

[seo.webmaster_verifications]
  google = "" # Optional, see https://search.google.com/search-console
  bing = "" # Optional, see https://www.bing.com/toolbox/webmaster/
  yandex = "" # Optional, see https://webmaster.yandex.com/
  alexa = "" # Optional, claiming retired (see note below)

[modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

[modules.hall_of_mirrors]
  enabled = true # Required in version 0.x.x
